version: "3"
services:
    frontend:
        image: sfrontend
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        links:
            - backend
        networks:
            - socialnetwork
    backend:
        image: sbackend
        restart: always
        ports:
            - "8800:8800"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongodb
        networks:
            - socialnetwork
    mongodb:
        image: mongo:4.0
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - socialnetwork
networks:
    socialnetwork:
        driver: bridge